name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install codecov
        pip install numpy
        pip install cython
        python setup.py build_ext --define CYTHON_TRACE
    - name: Test with pytest
      run: |
        pytest test.py
        
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
      with:
        flags: unittests # optional
        name: codecov-umbrella # optional
        verbose: true # optional (default = false)
