name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install codecov
        pip install cython
        python setup.py build_ext --define CYTHON_TRACE
    - name: Test with pytest
      run: |
        cython --annotate-coverage coverage.xml  cython_test_coverage/basic_cython.pyx
        coverage run test.py
        coverage xml
