name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov
        pip install numpy
        pip install cython
        python setup.py build_ext -inplace --define CYTHON_TRACE
    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=xml --cov-config=.coveragerc test.py
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: codecov-umbrella
        verbose: true
    
