name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Install dependencies
      run: |
        pip install codecov
        pip install cython
        python setup.py build_ext --define CYTHON_TRACE
    - name: Run unittests
      run: |
        cython --annotate-coverage coverage.xml  cython_test_coverage/basic_cython.pyx
        coverage run test.py
        coverage xml

    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
      with:
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)