name: Build
description: Rebuilds the C extensions
runs:
  using: composite
  steps:

    - name: Environment Detail
      run: |
        conda info
        conda list
      shell: bash -l {0}

    - name: Build Pandas
      run: |
        python setup.py build_ext --define CYTHON_TRACE
      shell: bash -l {0}
      